# Generated by Django 4.0.4 on 2022-05-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
