# Generated by Django 4.0.4 on 2022-05-12 09:45

from django.db import migrations


def add_answer_count(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    for question in Question.objects.all():
        question.answer_count = 2
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_answer_count'),
    ]

    operations = [
        migrations.RunPython(add_answer_count, reverse_code=migrations.RunPython.noop),
    ]
