# Generated by Django 4.0.4 on 2022-05-13 12:04

from django.db import migrations


def add_answer_count(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    for question in Question.objects.all():
        question.answer_count = Question.objects.get(pk=question.id).choice_set.count()
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220512_1245'),
    ]

    operations = [
        migrations.RunPython(add_answer_count, reverse_code=migrations.RunPython.noop),
    ]
